### ISSUE TITLE
Error:When I add the options you sugguges in the readme into makeFile,An error occurs.

### ISSUE THREAD

**Issue by crack521** [ryseek/simple-llama.cpp-python-wrapper#1]
![image](https://user-images.githubusercontent.com/7234477/229333491-8460e375-466b-4b0e-aca3-e5f6047caf43.png)

![image](https://user-images.githubusercontent.com/7234477/229333535-c99ea1cb-0ebd-4d0f-bb95-41c4c42cc066.png)

**Comment by ryseek** [comment]
@crack521 I think the problem is you have to use tabs instead of spaces for this new build target
